### PR TITLE
Use XWLPD firmware on devices that came with XWLPI

### PR DESCRIPTION
**Pull request by skyschub**
The XWLPI firmware is a XWLPD with some small interface modifications for the German market, so you will find XWLPI on all devices shipped in Germany.

### CODE REVIEW

**Comment by michaelwu** [comment]
Please add this to the list at https://github.com/denschub/android-device-galaxys2/blob/cbe19439f3ed0a73c37ac69c641e043db4115874/extract-files.sh#L51 and give it its own entry in the case statement. (just for consistency)

**Comment by skyschub** [comment]
Okay, done, thanks for the notice. But now we have a `FIRMWARE=XWLPD` in the XWLPI statement, I'm not sure this is nice.

**Comment by michaelwu** [comment]
You can change that too if you want. $FIRMWARE isn't currently checked for XWLPD so it doesn't matter at the moment.

**Comment by skyschub** [comment]
Just submitted another PR (#16). Feels better.

**Pull request merged**
